FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app .
# Копируем файл базы данных из исходной папки в корень образа
COPY okved.db .
RUN chmod 666 okved.db
ENTRYPOINT ["dotnet", "OkvedApi.dll"]